export { landingPage };

function landingPage(docObj) {
  const dialog = docObj.querySelector("#top-ten-dialog");
  const startButton = docObj.querySelector("#start");
  const showButton = docObj.querySelector("#show-top-ten");
  const closeButton = docObj.querySelector("dialog button");
  const resolutionButton = docObj.querySelector("#resolution");
  const gameSections = docObj.querySelectorAll(".game");
  const messageEl = docObj.querySelector("#message");
  const topTenMessageEl = docObj.querySelector("#top-ten-message");

  // get the game response and characters to setup the play
  const setupresponse = async (api) => {
    const headers = new Headers();
    headers.append("Content-Type", "application/json");
    try {
      const response = await fetch(`${api}/scene`, {
        method: "GET",
        headers: headers,
        credentials: "include",
      });
      console.log("response type: ", response.type);
      const contentType = response.headers.get("content-type");
      if (!contentType || !contentType.includes("application/json")) {
        throw new TypeError("Oops, we haven't got JSON!");
      }

      if ((response.ok || response.status === 304) && response.body) {
        const sceneData = await response.json();
        console.log(sceneData);
        const sceneId = sceneData.id;
        const secondResponse = await fetch(
          `${api}/scene/${sceneId}/characters`,
          {
            method: "GET",
            headers: headers,
            credentials: "include",
          }
        );
        if (
          (secondResponse.ok || secondResponse.status === 304) &&
          secondResponse.body
        ) {
          const characterData = await secondResponse.json();

          // prepare the scene image for display
          const sceneImage = updateSceneImage(docObj, sceneData);

          // display the characters
          let sceneCharacters = updateCharactersList(docObj, characterData);

          // prepare statement on the scene characters
          //const sceneCharacters = characterData.characters.reduce((acc, el, i, arr) => i < arr.length - 1 ? acc += ", " + el : acc += " and " + el)
          const h1 = `Let's find ${sceneCharacters}!`;
          const h2 = `This game will be timed! Will your time earn you a place in the top ten ?`;
          messageEl.innerText = h1;
          topTenMessageEl.innerText = h2;

          // add event listeners to the buttons
          // "Show the dialog" button opens the dialog modally
          showButton.addEventListener("click", () =>
            showTopTen(docObj, api, sceneId, dialog)
          );

          // "Close" button closes the dialog
          closeButton.addEventListener("click", () => {
            dialog.close();
          });

          resolutionButton.addEventListener("click", () => {
            // toggle the resolution from 100% of screen width to its normal high-res width
            const maxWidth = getComputedStyle(sceneImage)["max-width"];
            console.log(resolutionButton.offsetWidth)
            const toggleWidth = resolutionButton.offsetWidth;
            if (maxWidth !== "none") {
              sceneImage.style.maxWidth = "none"
              resolutionButton.classList.remove("offPos");
              resolutionButton.classList.add("onPos")
            } else {
              sceneImage.style.maxWidth = "calc(100% - 2rem)";
              resolutionButton.classList.add("offPos");
              resolutionButton.classList.remove("onPos")
            }
          })
          startButton.addEventListener("click", () => {
            // starts the game
            // and removes the unnecessary text areas from the page for game mode
            // and unblurs the scene
            
            const sceneSection = docObj.querySelector(".game > section:last-of-type");
            sceneSection.classList.remove("blur");
          });
          // show the sections on the page at last
          gameSections.forEach((el) => {
            el.toggleAttribute("hidden");
          });
        }
      } else {
        console.log(response);
        displayGeneralError(messageEl);
      }
    } catch (error) {
      console.log("caught an internal error");
      displayGeneralError(messageEl);
      console.error(error.message);
    }
  };

  setupresponse(API_URL); // this value is replaced at runtime by webpack (the real value is in the webpack config files)
}

function displayGeneralError(messageEl) {
  messageEl.innerHTML =
    "<h1>Sorry, something went wrong. We weren't able to setup a game for you to play. Please try again later.";
}

function updateCharactersList(docObj, characterData) {
  const charactersList = docObj.querySelector("#characters");

  let sceneCharacters = "";

  characterData.characters.forEach((el, i, arr) => {
    console.log(el);
    const listItem = docObj.createElement("li");
    const labelEl = docObj.createElement("label");
    labelEl.innerText = el.name;
    const pic = new Image();
    pic.src = el.url;
    pic.alt = el.name;
    sceneCharacters +=
      i >= 0 && i < arr.length - 1 ? `${el.name}, ` : `and ${el.name}`;

    labelEl.appendChild(pic);
    listItem.appendChild(labelEl);
    charactersList.appendChild(listItem);
  });
  return sceneCharacters;
}

function updateSceneImage(docObj, sceneData) {
  const sceneSection = docObj.querySelector(".game > section:last-of-type");
  console.log("ss: ",sceneSection)
  const image = new Image();
  image.src = sceneData.url;
  image.alt = "scene";
  sceneSection.classList.add("blur"); // we start out with a blurred image until the game is started officially
  sceneSection.appendChild(image);

  return image;
}

async function showTopTen(docObj, api, sceneId, dialog) {
  dialog.showModal();

  const headers = new Headers();
  headers.append("Content-Type", "application/json");
  const ttResponse = await fetch(`${api}/scene/${sceneId}/topten`, {
    method: "GET",
    headers: headers,
    credentials: "include",
  });
  if ((ttResponse.ok || ttResponse.status === 304) && ttResponse.body) {
    const topTen = await ttResponse.json();
    console.log(topTen);
    if (topTen.topTen.length === 0) {
      const paragraphEl = docObj.querySelector("#top-ten-dialog>p");
      paragraphEl.innerText = "No top scores recorded yet! Be the first!";
    } else {
      // display the list of players and their scores in the topTen.topTen array

      // and highlight the current player in the list
      const currentGameId = topTen.id;
    }
  }
}
/*

{
    "0": "accent-color",
    "1": "align-content",
    "2": "align-items",
    "3": "align-self",
    "4": "alignment-baseline",
    "5": "anchor-name",
    "6": "anchor-scope",
    "7": "animation-composition",
    "8": "animation-delay",
    "9": "animation-direction",
    "10": "animation-duration",
    "11": "animation-fill-mode",
    "12": "animation-iteration-count",
    "13": "animation-name",
    "14": "animation-play-state",
    "15": "animation-range-end",
    "16": "animation-range-start",
    "17": "animation-timeline",
    "18": "animation-timing-function",
    "19": "app-region",
    "20": "appearance",
    "21": "backdrop-filter",
    "22": "backface-visibility",
    "23": "background-attachment",
    "24": "background-blend-mode",
    "25": "background-clip",
    "26": "background-color",
    "27": "background-image",
    "28": "background-origin",
    "29": "background-position",
    "30": "background-repeat",
    "31": "background-size",
    "32": "baseline-shift",
    "33": "baseline-source",
    "34": "block-size",
    "35": "border-block-end-color",
    "36": "border-block-end-style",
    "37": "border-block-end-width",
    "38": "border-block-start-color",
    "39": "border-block-start-style",
    "40": "border-block-start-width",
    "41": "border-bottom-color",
    "42": "border-bottom-left-radius",
    "43": "border-bottom-right-radius",
    "44": "border-bottom-style",
    "45": "border-bottom-width",
    "46": "border-collapse",
    "47": "border-end-end-radius",
    "48": "border-end-start-radius",
    "49": "border-image-outset",
    "50": "border-image-repeat",
    "51": "border-image-slice",
    "52": "border-image-source",
    "53": "border-image-width",
    "54": "border-inline-end-color",
    "55": "border-inline-end-style",
    "56": "border-inline-end-width",
    "57": "border-inline-start-color",
    "58": "border-inline-start-style",
    "59": "border-inline-start-width",
    "60": "border-left-color",
    "61": "border-left-style",
    "62": "border-left-width",
    "63": "border-right-color",
    "64": "border-right-style",
    "65": "border-right-width",
    "66": "border-start-end-radius",
    "67": "border-start-start-radius",
    "68": "border-top-color",
    "69": "border-top-left-radius",
    "70": "border-top-right-radius",
    "71": "border-top-style",
    "72": "border-top-width",
    "73": "bottom",
    "74": "box-decoration-break",
    "75": "box-shadow",
    "76": "box-sizing",
    "77": "break-after",
    "78": "break-before",
    "79": "break-inside",
    "80": "buffered-rendering",
    "81": "caption-side",
    "82": "caret-animation",
    "83": "caret-color",
    "84": "clear",
    "85": "clip",
    "86": "clip-path",
    "87": "clip-rule",
    "88": "color",
    "89": "color-interpolation",
    "90": "color-interpolation-filters",
    "91": "color-rendering",
    "92": "column-count",
    "93": "column-gap",
    "94": "column-rule-color",
    "95": "column-rule-style",
    "96": "column-rule-width",
    "97": "column-span",
    "98": "column-width",
    "99": "contain-intrinsic-block-size",
    "100": "contain-intrinsic-height",
    "101": "contain-intrinsic-inline-size",
    "102": "contain-intrinsic-size",
    "103": "contain-intrinsic-width",
    "104": "container-name",
    "105": "container-type",
    "106": "content",
    "107": "corner-bottom-left-shape",
    "108": "corner-bottom-right-shape",
    "109": "corner-end-end-shape",
    "110": "corner-end-start-shape",
    "111": "corner-start-end-shape",
    "112": "corner-start-start-shape",
    "113": "corner-top-left-shape",
    "114": "corner-top-right-shape",
    "115": "cursor",
    "116": "cx",
    "117": "cy",
    "118": "d",
    "119": "direction",
    "120": "display",
    "121": "dominant-baseline",
    "122": "dynamic-range-limit",
    "123": "empty-cells",
    "124": "field-sizing",
    "125": "fill",
    "126": "fill-opacity",
    "127": "fill-rule",
    "128": "filter",
    "129": "flex-basis",
    "130": "flex-direction",
    "131": "flex-grow",
    "132": "flex-shrink",
    "133": "flex-wrap",
    "134": "float",
    "135": "flood-color",
    "136": "flood-opacity",
    "137": "font-family",
    "138": "font-kerning",
    "139": "font-optical-sizing",
    "140": "font-palette",
    "141": "font-size",
    "142": "font-size-adjust",
    "143": "font-stretch",
    "144": "font-style",
    "145": "font-synthesis-small-caps",
    "146": "font-synthesis-style",
    "147": "font-synthesis-weight",
    "148": "font-variant",
    "149": "font-variant-alternates",
    "150": "font-variant-caps",
    "151": "font-variant-east-asian",
    "152": "font-variant-emoji",
    "153": "font-variant-ligatures",
    "154": "font-variant-numeric",
    "155": "font-variant-position",
    "156": "font-weight",
    "157": "grid-auto-columns",
    "158": "grid-auto-flow",
    "159": "grid-auto-rows",
    "160": "grid-column-end",
    "161": "grid-column-start",
    "162": "grid-row-end",
    "163": "grid-row-start",
    "164": "grid-template-areas",
    "165": "grid-template-columns",
    "166": "grid-template-rows",
    "167": "height",
    "168": "hyphenate-character",
    "169": "hyphenate-limit-chars",
    "170": "hyphens",
    "171": "image-orientation",
    "172": "image-rendering",
    "173": "initial-letter",
    "174": "inline-size",
    "175": "inset-block-end",
    "176": "inset-block-start",
    "177": "inset-inline-end",
    "178": "inset-inline-start",
    "179": "interactivity",
    "180": "interest-delay-end",
    "181": "interest-delay-start",
    "182": "interpolate-size",
    "183": "isolation",
    "184": "justify-content",
    "185": "justify-items",
    "186": "justify-self",
    "187": "left",
    "188": "letter-spacing",
    "189": "lighting-color",
    "190": "line-break",
    "191": "line-height",
    "192": "list-style-image",
    "193": "list-style-position",
    "194": "list-style-type",
    "195": "margin-block-end",
    "196": "margin-block-start",
    "197": "margin-bottom",
    "198": "margin-inline-end",
    "199": "margin-inline-start",
    "200": "margin-left",
    "201": "margin-right",
    "202": "margin-top",
    "203": "marker-end",
    "204": "marker-mid",
    "205": "marker-start",
    "206": "mask-clip",
    "207": "mask-composite",
    "208": "mask-image",
    "209": "mask-mode",
    "210": "mask-origin",
    "211": "mask-position",
    "212": "mask-repeat",
    "213": "mask-size",
    "214": "mask-type",
    "215": "math-depth",
    "216": "math-shift",
    "217": "math-style",
    "218": "max-block-size",
    "219": "max-height",
    "220": "max-inline-size",
    "221": "max-width",
    "222": "min-block-size",
    "223": "min-height",
    "224": "min-inline-size",
    "225": "min-width",
    "226": "mix-blend-mode",
    "227": "object-fit",
    "228": "object-position",
    "229": "object-view-box",
    "230": "offset-anchor",
    "231": "offset-distance",
    "232": "offset-path",
    "233": "offset-position",
    "234": "offset-rotate",
    "235": "opacity",
    "236": "order",
    "237": "orphans",
    "238": "outline-color",
    "239": "outline-offset",
    "240": "outline-style",
    "241": "outline-width",
    "242": "overflow-anchor",
    "243": "overflow-block",
    "244": "overflow-clip-margin",
    "245": "overflow-inline",
    "246": "overflow-wrap",
    "247": "overflow-x",
    "248": "overflow-y",
    "249": "overlay",
    "250": "overscroll-behavior-block",
    "251": "overscroll-behavior-inline",
    "252": "padding-block-end",
    "253": "padding-block-start",
    "254": "padding-bottom",
    "255": "padding-inline-end",
    "256": "padding-inline-start",
    "257": "padding-left",
    "258": "padding-right",
    "259": "padding-top",
    "260": "paint-order",
    "261": "perspective",
    "262": "perspective-origin",
    "263": "pointer-events",
    "264": "position",
    "265": "position-anchor",
    "266": "position-area",
    "267": "position-try-fallbacks",
    "268": "position-try-order",
    "269": "position-visibility",
    "270": "print-color-adjust",
    "271": "r",
    "272": "reading-flow",
    "273": "reading-order",
    "274": "resize",
    "275": "right",
    "276": "rotate",
    "277": "row-gap",
    "278": "ruby-align",
    "279": "ruby-position",
    "280": "rx",
    "281": "ry",
    "282": "scale",
    "283": "scroll-behavior",
    "284": "scroll-initial-target",
    "285": "scroll-margin-block-end",
    "286": "scroll-margin-block-start",
    "287": "scroll-margin-inline-end",
    "288": "scroll-margin-inline-start",
    "289": "scroll-marker-group",
    "290": "scroll-padding-block-end",
    "291": "scroll-padding-block-start",
    "292": "scroll-padding-inline-end",
    "293": "scroll-padding-inline-start",
    "294": "scroll-target-group",
    "295": "scroll-timeline-axis",
    "296": "scroll-timeline-name",
    "297": "scrollbar-color",
    "298": "scrollbar-gutter",
    "299": "scrollbar-width",
    "300": "shape-image-threshold",
    "301": "shape-margin",
    "302": "shape-outside",
    "303": "shape-rendering",
    "304": "speak",
    "305": "stop-color",
    "306": "stop-opacity",
    "307": "stroke",
    "308": "stroke-dasharray",
    "309": "stroke-dashoffset",
    "310": "stroke-linecap",
    "311": "stroke-linejoin",
    "312": "stroke-miterlimit",
    "313": "stroke-opacity",
    "314": "stroke-width",
    "315": "tab-size",
    "316": "table-layout",
    "317": "text-align",
    "318": "text-align-last",
    "319": "text-anchor",
    "320": "text-autospace",
    "321": "text-box-edge",
    "322": "text-box-trim",
    "323": "text-decoration",
    "324": "text-decoration-color",
    "325": "text-decoration-line",
    "326": "text-decoration-skip-ink",
    "327": "text-decoration-style",
    "328": "text-emphasis-color",
    "329": "text-emphasis-position",
    "330": "text-emphasis-style",
    "331": "text-indent",
    "332": "text-overflow",
    "333": "text-rendering",
    "334": "text-shadow",
    "335": "text-size-adjust",
    "336": "text-spacing-trim",
    "337": "text-transform",
    "338": "text-underline-position",
    "339": "text-wrap-mode",
    "340": "text-wrap-style",
    "341": "timeline-scope",
    "342": "top",
    "343": "touch-action",
    "344": "transform",
    "345": "transform-origin",
    "346": "transform-style",
    "347": "transition-behavior",
    "348": "transition-delay",
    "349": "transition-duration",
    "350": "transition-property",
    "351": "transition-timing-function",
    "352": "translate",
    "353": "unicode-bidi",
    "354": "user-select",
    "355": "vector-effect",
    "356": "vertical-align",
    "357": "view-timeline-axis",
    "358": "view-timeline-inset",
    "359": "view-timeline-name",
    "360": "view-transition-class",
    "361": "view-transition-group",
    "362": "view-transition-name",
    "363": "visibility",
    "364": "white-space-collapse",
    "365": "widows",
    "366": "width",
    "367": "will-change",
    "368": "word-break",
    "369": "word-spacing",
    "370": "writing-mode",
    "371": "x",
    "372": "y",
    "373": "z-index",
    "374": "zoom",
    "375": "-webkit-border-horizontal-spacing",
    "376": "-webkit-border-image",
    "377": "-webkit-border-vertical-spacing",
    "378": "-webkit-box-align",
    "379": "-webkit-box-decoration-break",
    "380": "-webkit-box-direction",
    "381": "-webkit-box-flex",
    "382": "-webkit-box-ordinal-group",
    "383": "-webkit-box-orient",
    "384": "-webkit-box-pack",
    "385": "-webkit-box-reflect",
    "386": "-webkit-font-smoothing",
    "387": "-webkit-line-break",
    "388": "-webkit-line-clamp",
    "389": "-webkit-locale",
    "390": "-webkit-mask-box-image",
    "391": "-webkit-mask-box-image-outset",
    "392": "-webkit-mask-box-image-repeat",
    "393": "-webkit-mask-box-image-slice",
    "394": "-webkit-mask-box-image-source",
    "395": "-webkit-mask-box-image-width",
    "396": "-webkit-rtl-ordering",
    "397": "-webkit-tap-highlight-color",
    "398": "-webkit-text-combine",
    "399": "-webkit-text-decorations-in-effect",
    "400": "-webkit-text-fill-color",
    "401": "-webkit-text-orientation",
    "402": "-webkit-text-security",
    "403": "-webkit-text-stroke-color",
    "404": "-webkit-text-stroke-width",
    "405": "-webkit-user-drag",
    "406": "-webkit-user-modify",
    "407": "-webkit-writing-mode",
    "accentColor": "auto",
    "additiveSymbols": "",
    "alignContent": "normal",
    "alignItems": "normal",
    "alignSelf": "auto",
    "alignmentBaseline": "auto",
    "all": "",
    "anchorName": "none",
    "anchorScope": "none",
    "animation": "none 0s ease 0s 1 normal none running",
    "animationComposition": "replace",
    "animationDelay": "0s",
    "animationDirection": "normal",
    "animationDuration": "0s",
    "animationFillMode": "none",
    "animationIterationCount": "1",
    "animationName": "none",
    "animationPlayState": "running",
    "animationRange": "normal",
    "animationRangeEnd": "normal",
    "animationRangeStart": "normal",
    "animationTimeline": "auto",
    "animationTimingFunction": "ease",
    "appRegion": "none",
    "appearance": "none",
    "ascentOverride": "",
    "aspectRatio": "auto",
    "backdropFilter": "none",
    "backfaceVisibility": "visible",
    "background": "rgba(0, 0, 0, 0) none repeat scroll 0% 0% / auto padding-box border-box",
    "backgroundAttachment": "scroll",
    "backgroundBlendMode": "normal",
    "backgroundClip": "border-box",
    "backgroundColor": "rgba(0, 0, 0, 0)",
    "backgroundImage": "none",
    "backgroundOrigin": "padding-box",
    "backgroundPosition": "0% 0%",
    "backgroundPositionX": "0%",
    "backgroundPositionY": "0%",
    "backgroundRepeat": "repeat",
    "backgroundSize": "auto",
    "basePalette": "",
    "baselineShift": "0px",
    "baselineSource": "auto",
    "blockSize": "629.869px",
    "border": "2px ridge rgb(0, 0, 0)",
    "borderBlock": "2px ridge rgb(0, 0, 0)",
    "borderBlockColor": "rgb(0, 0, 0)",
    "borderBlockEnd": "2px ridge rgb(0, 0, 0)",
    "borderBlockEndColor": "rgb(0, 0, 0)",
    "borderBlockEndStyle": "ridge",
    "borderBlockEndWidth": "2px",
    "borderBlockStart": "2px ridge rgb(0, 0, 0)",
    "borderBlockStartColor": "rgb(0, 0, 0)",
    "borderBlockStartStyle": "ridge",
    "borderBlockStartWidth": "2px",
    "borderBlockStyle": "ridge",
    "borderBlockWidth": "2px",
    "borderBottom": "2px ridge rgb(0, 0, 0)",
    "borderBottomColor": "rgb(0, 0, 0)",
    "borderBottomLeftRadius": "0px",
    "borderBottomRightRadius": "0px",
    "borderBottomStyle": "ridge",
    "borderBottomWidth": "2px",
    "borderCollapse": "separate",
    "borderColor": "rgb(0, 0, 0)",
    "borderEndEndRadius": "0px",
    "borderEndStartRadius": "0px",
    "borderImage": "none",
    "borderImageOutset": "0",
    "borderImageRepeat": "stretch",
    "borderImageSlice": "100%",
    "borderImageSource": "none",
    "borderImageWidth": "1",
    "borderInline": "2px ridge rgb(0, 0, 0)",
    "borderInlineColor": "rgb(0, 0, 0)",
    "borderInlineEnd": "2px ridge rgb(0, 0, 0)",
    "borderInlineEndColor": "rgb(0, 0, 0)",
    "borderInlineEndStyle": "ridge",
    "borderInlineEndWidth": "2px",
    "borderInlineStart": "2px ridge rgb(0, 0, 0)",
    "borderInlineStartColor": "rgb(0, 0, 0)",
    "borderInlineStartStyle": "ridge",
    "borderInlineStartWidth": "2px",
    "borderInlineStyle": "ridge",
    "borderInlineWidth": "2px",
    "borderLeft": "2px ridge rgb(0, 0, 0)",
    "borderLeftColor": "rgb(0, 0, 0)",
    "borderLeftStyle": "ridge",
    "borderLeftWidth": "2px",
    "borderRadius": "0px",
    "borderRight": "2px ridge rgb(0, 0, 0)",
    "borderRightColor": "rgb(0, 0, 0)",
    "borderRightStyle": "ridge",
    "borderRightWidth": "2px",
    "borderSpacing": "0px",
    "borderStartEndRadius": "0px",
    "borderStartStartRadius": "0px",
    "borderStyle": "ridge",
    "borderTop": "2px ridge rgb(0, 0, 0)",
    "borderTopColor": "rgb(0, 0, 0)",
    "borderTopLeftRadius": "0px",
    "borderTopRightRadius": "0px",
    "borderTopStyle": "ridge",
    "borderTopWidth": "2px",
    "borderWidth": "2px",
    "bottom": "auto",
    "boxDecorationBreak": "slice",
    "boxShadow": "none",
    "boxSizing": "border-box",
    "breakAfter": "auto",
    "breakBefore": "auto",
    "breakInside": "auto",
    "bufferedRendering": "auto",
    "captionSide": "top",
    "caretAnimation": "auto",
    "caretColor": "rgb(0, 0, 0)",
    "clear": "none",
    "clip": "auto",
    "clipPath": "none",
    "clipRule": "nonzero",
    "color": "rgb(0, 0, 0)",
    "colorInterpolation": "srgb",
    "colorInterpolationFilters": "linearrgb",
    "colorRendering": "auto",
    "colorScheme": "normal",
    "columnCount": "auto",
    "columnFill": "balance",
    "columnGap": "normal",
    "columnRule": "0px rgb(0, 0, 0)",
    "columnRuleColor": "rgb(0, 0, 0)",
    "columnRuleStyle": "none",
    "columnRuleWidth": "0px",
    "columnSpan": "none",
    "columnWidth": "auto",
    "columns": "auto",
    "contain": "none",
    "containIntrinsicBlockSize": "none",
    "containIntrinsicHeight": "none",
    "containIntrinsicInlineSize": "none",
    "containIntrinsicSize": "none",
    "containIntrinsicWidth": "none",
    "container": "none",
    "containerName": "none",
    "containerType": "normal",
    "content": "normal",
    "contentVisibility": "visible",
    "cornerBlockEndShape": "round",
    "cornerBlockStartShape": "round",
    "cornerBottomLeftShape": "round",
    "cornerBottomRightShape": "round",
    "cornerBottomShape": "round",
    "cornerEndEndShape": "round",
    "cornerEndStartShape": "round",
    "cornerInlineEndShape": "round",
    "cornerInlineStartShape": "round",
    "cornerLeftShape": "round",
    "cornerRightShape": "round",
    "cornerShape": "round",
    "cornerStartEndShape": "round",
    "cornerStartStartShape": "round",
    "cornerTopLeftShape": "round",
    "cornerTopRightShape": "round",
    "cornerTopShape": "round",
    "counterIncrement": "none",
    "counterReset": "none",
    "counterSet": "none",
    "cursor": "auto",
    "cx": "0px",
    "cy": "0px",
    "d": "none",
    "descentOverride": "",
    "direction": "ltr",
    "display": "block",
    "dominantBaseline": "auto",
    "dynamicRangeLimit": "no-limit",
    "emptyCells": "show",
    "fallback": "",
    "fieldSizing": "fixed",
    "fill": "rgb(0, 0, 0)",
    "fillOpacity": "1",
    "fillRule": "nonzero",
    "filter": "none",
    "flex": "0 1 auto",
    "flexBasis": "auto",
    "flexDirection": "row",
    "flexFlow": "row nowrap",
    "flexGrow": "0",
    "flexShrink": "1",
    "flexWrap": "nowrap",
    "float": "none",
    "floodColor": "rgb(0, 0, 0)",
    "floodOpacity": "1",
    "font": "16px \"Times New Roman\"",
    "fontDisplay": "",
    "fontFamily": "\"Times New Roman\"",
    "fontFeatureSettings": "normal",
    "fontKerning": "auto",
    "fontOpticalSizing": "auto",
    "fontPalette": "normal",
    "fontSize": "16px",
    "fontSizeAdjust": "none",
    "fontStretch": "100%",
    "fontStyle": "normal",
    "fontSynthesis": "weight style small-caps",
    "fontSynthesisSmallCaps": "auto",
    "fontSynthesisStyle": "auto",
    "fontSynthesisWeight": "auto",
    "fontVariant": "normal",
    "fontVariantAlternates": "normal",
    "fontVariantCaps": "normal",
    "fontVariantEastAsian": "normal",
    "fontVariantEmoji": "normal",
    "fontVariantLigatures": "normal",
    "fontVariantNumeric": "normal",
    "fontVariantPosition": "normal",
    "fontVariationSettings": "normal",
    "fontWeight": "400",
    "forcedColorAdjust": "auto",
    "gap": "normal",
    "grid": "none / none / none / row / auto / auto",
    "gridArea": "auto / 1 / auto / -1",
    "gridAutoColumns": "auto",
    "gridAutoFlow": "row",
    "gridAutoRows": "auto",
    "gridColumn": "1 / -1",
    "gridColumnEnd": "-1",
    "gridColumnGap": "normal",
    "gridColumnStart": "1",
    "gridGap": "normal",
    "gridRow": "auto",
    "gridRowEnd": "auto",
    "gridRowGap": "normal",
    "gridRowStart": "auto",
    "gridTemplate": "none",
    "gridTemplateAreas": "none",
    "gridTemplateColumns": "none",
    "gridTemplateRows": "none",
    "height": "629.869px",
    "hyphenateCharacter": "auto",
    "hyphenateLimitChars": "auto",
    "hyphens": "manual",
    "imageOrientation": "from-image",
    "imageRendering": "auto",
    "inherits": "",
    "initialLetter": "normal",
    "initialValue": "",
    "inlineSize": "952.794px",
    "inset": "auto",
    "insetBlock": "auto",
    "insetBlockEnd": "auto",
    "insetBlockStart": "auto",
    "insetInline": "auto",
    "insetInlineEnd": "auto",
    "insetInlineStart": "auto",
    "interactivity": "auto",
    "interestDelay": "normal",
    "interestDelayEnd": "normal",
    "interestDelayStart": "normal",
    "interpolateSize": "numeric-only",
    "isolation": "auto",
    "justifyContent": "normal",
    "justifyItems": "normal",
    "justifySelf": "auto",
    "left": "auto",
    "letterSpacing": "normal",
    "lightingColor": "rgb(255, 255, 255)",
    "lineBreak": "auto",
    "lineGapOverride": "",
    "lineHeight": "normal",
    "listStyle": "outside none disc",
    "listStyleImage": "none",
    "listStylePosition": "outside",
    "listStyleType": "disc",
    "margin": "16px",
    "marginBlock": "16px",
    "marginBlockEnd": "16px",
    "marginBlockStart": "16px",
    "marginBottom": "16px",
    "marginInline": "16px",
    "marginInlineEnd": "16px",
    "marginInlineStart": "16px",
    "marginLeft": "16px",
    "marginRight": "16px",
    "marginTop": "16px",
    "marker": "none",
    "markerEnd": "none",
    "markerMid": "none",
    "markerStart": "none",
    "mask": "none",
    "maskClip": "border-box",
    "maskComposite": "add",
    "maskImage": "none",
    "maskMode": "match-source",
    "maskOrigin": "border-box",
    "maskPosition": "0% 0%",
    "maskRepeat": "repeat",
    "maskSize": "auto",
    "maskType": "luminance",
    "mathDepth": "0",
    "mathShift": "normal",
    "mathStyle": "normal",
    "maxBlockSize": "none",
    "maxHeight": "none",
    "maxInlineSize": "calc(100% - 32px)",
    "maxWidth": "calc(100% - 32px)",
    "minBlockSize": "auto",
    "minHeight": "auto",
    "minInlineSize": "auto",
    "minWidth": "auto",
    "mixBlendMode": "normal",
    "navigation": "",
    "negative": "",
    "objectFit": "fill",
    "objectPosition": "50% 50%",
    "objectViewBox": "none",
    "offset": "none 0px auto 0deg",
    "offsetAnchor": "auto",
    "offsetDistance": "0px",
    "offsetPath": "none",
    "offsetPosition": "normal",
    "offsetRotate": "auto 0deg",
    "opacity": "1",
    "order": "0",
    "orphans": "2",
    "outline": "rgb(0, 0, 0) none 0px",
    "outlineColor": "rgb(0, 0, 0)",
    "outlineOffset": "0px",
    "outlineStyle": "none",
    "outlineWidth": "0px",
    "overflow": "clip",
    "overflowAnchor": "auto",
    "overflowBlock": "clip",
    "overflowClipMargin": "content-box",
    "overflowInline": "clip",
    "overflowWrap": "normal",
    "overflowX": "clip",
    "overflowY": "clip",
    "overlay": "none",
    "overrideColors": "",
    "overscrollBehavior": "auto",
    "overscrollBehaviorBlock": "auto",
    "overscrollBehaviorInline": "auto",
    "overscrollBehaviorX": "auto",
    "overscrollBehaviorY": "auto",
    "pad": "",
    "padding": "2px",
    "paddingBlock": "2px",
    "paddingBlockEnd": "2px",
    "paddingBlockStart": "2px",
    "paddingBottom": "2px",
    "paddingInline": "2px",
    "paddingInlineEnd": "2px",
    "paddingInlineStart": "2px",
    "paddingLeft": "2px",
    "paddingRight": "2px",
    "paddingTop": "2px",
    "page": "auto",
    "pageBreakAfter": "auto",
    "pageBreakBefore": "auto",
    "pageBreakInside": "auto",
    "pageOrientation": "",
    "paintOrder": "normal",
    "perspective": "none",
    "perspectiveOrigin": "476.394px 314.931px",
    "placeContent": "normal",
    "placeItems": "normal",
    "placeSelf": "auto",
    "pointerEvents": "auto",
    "position": "static",
    "positionAnchor": "auto",
    "positionArea": "none",
    "positionTry": "none",
    "positionTryFallbacks": "none",
    "positionTryOrder": "normal",
    "positionVisibility": "anchors-visible",
    "prefix": "",
    "printColorAdjust": "economy",
    "quotes": "auto",
    "r": "0px",
    "range": "",
    "readingFlow": "normal",
    "readingOrder": "0",
    "resize": "none",
    "result": "",
    "right": "auto",
    "rotate": "none",
    "rowGap": "normal",
    "rubyAlign": "space-around",
    "rubyPosition": "over",
    "rx": "auto",
    "ry": "auto",
    "scale": "none",
    "scrollBehavior": "auto",
    "scrollInitialTarget": "none",
    "scrollMargin": "0px",
    "scrollMarginBlock": "0px",
    "scrollMarginBlockEnd": "0px",
    "scrollMarginBlockStart": "0px",
    "scrollMarginBottom": "0px",
    "scrollMarginInline": "0px",
    "scrollMarginInlineEnd": "0px",
    "scrollMarginInlineStart": "0px",
    "scrollMarginLeft": "0px",
    "scrollMarginRight": "0px",
    "scrollMarginTop": "0px",
    "scrollMarkerGroup": "none",
    "scrollPadding": "auto",
    "scrollPaddingBlock": "auto",
    "scrollPaddingBlockEnd": "auto",
    "scrollPaddingBlockStart": "auto",
    "scrollPaddingBottom": "auto",
    "scrollPaddingInline": "auto",
    "scrollPaddingInlineEnd": "auto",
    "scrollPaddingInlineStart": "auto",
    "scrollPaddingLeft": "auto",
    "scrollPaddingRight": "auto",
    "scrollPaddingTop": "auto",
    "scrollSnapAlign": "none",
    "scrollSnapStop": "normal",
    "scrollSnapType": "none",
    "scrollTargetGroup": "none",
    "scrollTimeline": "none",
    "scrollTimelineAxis": "block",
    "scrollTimelineName": "none",
    "scrollbarColor": "auto",
    "scrollbarGutter": "auto",
    "scrollbarWidth": "auto",
    "shapeImageThreshold": "0",
    "shapeMargin": "0px",
    "shapeOutside": "none",
    "shapeRendering": "auto",
    "size": "",
    "sizeAdjust": "",
    "speak": "normal",
    "speakAs": "",
    "src": "",
    "stopColor": "rgb(0, 0, 0)",
    "stopOpacity": "1",
    "stroke": "none",
    "strokeDasharray": "none",
    "strokeDashoffset": "0px",
    "strokeLinecap": "butt",
    "strokeLinejoin": "miter",
    "strokeMiterlimit": "4",
    "strokeOpacity": "1",
    "strokeWidth": "1px",
    "suffix": "",
    "symbols": "",
    "syntax": "",
    "system": "",
    "tabSize": "8",
    "tableLayout": "auto",
    "textAlign": "start",
    "textAlignLast": "auto",
    "textAnchor": "start",
    "textAutospace": "no-autospace",
    "textBox": "normal",
    "textBoxEdge": "auto",
    "textBoxTrim": "none",
    "textCombineUpright": "none",
    "textDecoration": "none",
    "textDecorationColor": "rgb(0, 0, 0)",
    "textDecorationLine": "none",
    "textDecorationSkipInk": "auto",
    "textDecorationStyle": "solid",
    "textDecorationThickness": "auto",
    "textEmphasis": "none rgb(0, 0, 0)",
    "textEmphasisColor": "rgb(0, 0, 0)",
    "textEmphasisPosition": "over",
    "textEmphasisStyle": "none",
    "textIndent": "0px",
    "textOrientation": "mixed",
    "textOverflow": "clip",
    "textRendering": "auto",
    "textShadow": "none",
    "textSizeAdjust": "auto",
    "textSpacingTrim": "normal",
    "textTransform": "none",
    "textUnderlineOffset": "auto",
    "textUnderlinePosition": "auto",
    "textWrap": "wrap",
    "textWrapMode": "wrap",
    "textWrapStyle": "auto",
    "timelineScope": "none",
    "top": "auto",
    "touchAction": "auto",
    "transform": "none",
    "transformBox": "view-box",
    "transformOrigin": "476.397px 314.934px",
    "transformStyle": "flat",
    "transition": "all",
    "transitionBehavior": "normal",
    "transitionDelay": "0s",
    "transitionDuration": "0s",
    "transitionProperty": "all",
    "transitionTimingFunction": "ease",
    "translate": "none",
    "types": "",
    "unicodeBidi": "normal",
    "unicodeRange": "",
    "userSelect": "auto",
    "vectorEffect": "none",
    "verticalAlign": "baseline",
    "viewTimeline": "none",
    "viewTimelineAxis": "block",
    "viewTimelineInset": "auto",
    "viewTimelineName": "none",
    "viewTransitionClass": "none",
    "viewTransitionGroup": "normal",
    "viewTransitionName": "none",
    "visibility": "visible",
    "webkitAlignContent": "normal",
    "webkitAlignItems": "normal",
    "webkitAlignSelf": "auto",
    "webkitAnimation": "none 0s ease 0s 1 normal none running",
    "webkitAnimationDelay": "0s",
    "webkitAnimationDirection": "normal",
    "webkitAnimationDuration": "0s",
    "webkitAnimationFillMode": "none",
    "webkitAnimationIterationCount": "1",
    "webkitAnimationName": "none",
    "webkitAnimationPlayState": "running",
    "webkitAnimationTimingFunction": "ease",
    "webkitAppRegion": "none",
    "webkitAppearance": "none",
    "webkitBackfaceVisibility": "visible",
    "webkitBackgroundClip": "border-box",
    "webkitBackgroundOrigin": "padding-box",
    "webkitBackgroundSize": "auto",
    "webkitBorderAfter": "2px ridge rgb(0, 0, 0)",
    "webkitBorderAfterColor": "rgb(0, 0, 0)",
    "webkitBorderAfterStyle": "ridge",
    "webkitBorderAfterWidth": "2px",
    "webkitBorderBefore": "2px ridge rgb(0, 0, 0)",
    "webkitBorderBeforeColor": "rgb(0, 0, 0)",
    "webkitBorderBeforeStyle": "ridge",
    "webkitBorderBeforeWidth": "2px",
    "webkitBorderBottomLeftRadius": "0px",
    "webkitBorderBottomRightRadius": "0px",
    "webkitBorderEnd": "2px ridge rgb(0, 0, 0)",
    "webkitBorderEndColor": "rgb(0, 0, 0)",
    "webkitBorderEndStyle": "ridge",
    "webkitBorderEndWidth": "2px",
    "webkitBorderHorizontalSpacing": "0px",
    "webkitBorderImage": "none",
    "webkitBorderRadius": "0px",
    "webkitBorderStart": "2px ridge rgb(0, 0, 0)",
    "webkitBorderStartColor": "rgb(0, 0, 0)",
    "webkitBorderStartStyle": "ridge",
    "webkitBorderStartWidth": "2px",
    "webkitBorderTopLeftRadius": "0px",
    "webkitBorderTopRightRadius": "0px",
    "webkitBorderVerticalSpacing": "0px",
    "webkitBoxAlign": "stretch",
    "webkitBoxDecorationBreak": "slice",
    "webkitBoxDirection": "normal",
    "webkitBoxFlex": "0",
    "webkitBoxOrdinalGroup": "1",
    "webkitBoxOrient": "horizontal",
    "webkitBoxPack": "start",
    "webkitBoxReflect": "none",
    "webkitBoxShadow": "none",
    "webkitBoxSizing": "border-box",
    "webkitClipPath": "none",
    "webkitColumnBreakAfter": "auto",
    "webkitColumnBreakBefore": "auto",
    "webkitColumnBreakInside": "auto",
    "webkitColumnCount": "auto",
    "webkitColumnGap": "normal",
    "webkitColumnRule": "0px rgb(0, 0, 0)",
    "webkitColumnRuleColor": "rgb(0, 0, 0)",
    "webkitColumnRuleStyle": "none",
    "webkitColumnRuleWidth": "0px",
    "webkitColumnSpan": "none",
    "webkitColumnWidth": "auto",
    "webkitColumns": "auto",
    "webkitFilter": "none",
    "webkitFlex": "0 1 auto",
    "webkitFlexBasis": "auto",
    "webkitFlexDirection": "row",
    "webkitFlexFlow": "row nowrap",
    "webkitFlexGrow": "0",
    "webkitFlexShrink": "1",
    "webkitFlexWrap": "nowrap",
    "webkitFontFeatureSettings": "normal",
    "webkitFontSmoothing": "auto",
    "webkitHyphenateCharacter": "auto",
    "webkitJustifyContent": "normal",
    "webkitLineBreak": "auto",
    "webkitLineClamp": "none",
    "webkitLocale": "\"en\"",
    "webkitLogicalHeight": "629.869px",
    "webkitLogicalWidth": "952.794px",
    "webkitMarginAfter": "16px",
    "webkitMarginBefore": "16px",
    "webkitMarginEnd": "16px",
    "webkitMarginStart": "16px",
    "webkitMask": "none",
    "webkitMaskBoxImage": "none",
    "webkitMaskBoxImageOutset": "0",
    "webkitMaskBoxImageRepeat": "stretch",
    "webkitMaskBoxImageSlice": "0 fill",
    "webkitMaskBoxImageSource": "none",
    "webkitMaskBoxImageWidth": "auto",
    "webkitMaskClip": "border-box",
    "webkitMaskComposite": "add",
    "webkitMaskImage": "none",
    "webkitMaskOrigin": "border-box",
    "webkitMaskPosition": "0% 0%",
    "webkitMaskPositionX": "0%",
    "webkitMaskPositionY": "0%",
    "webkitMaskRepeat": "repeat",
    "webkitMaskSize": "auto",
    "webkitMaxLogicalHeight": "none",
    "webkitMaxLogicalWidth": "calc(100% - 32px)",
    "webkitMinLogicalHeight": "auto",
    "webkitMinLogicalWidth": "auto",
    "webkitOpacity": "1",
    "webkitOrder": "0",
    "webkitPaddingAfter": "2px",
    "webkitPaddingBefore": "2px",
    "webkitPaddingEnd": "2px",
    "webkitPaddingStart": "2px",
    "webkitPerspective": "none",
    "webkitPerspectiveOrigin": "476.394px 314.931px",
    "webkitPerspectiveOriginX": "",
    "webkitPerspectiveOriginY": "",
    "webkitPrintColorAdjust": "economy",
    "webkitRtlOrdering": "logical",
    "webkitRubyPosition": "before",
    "webkitShapeImageThreshold": "0",
    "webkitShapeMargin": "0px",
    "webkitShapeOutside": "none",
    "webkitTapHighlightColor": "rgba(0, 0, 0, 0.18)",
    "webkitTextCombine": "none",
    "webkitTextDecorationsInEffect": "none",
    "webkitTextEmphasis": "none rgb(0, 0, 0)",
    "webkitTextEmphasisColor": "rgb(0, 0, 0)",
    "webkitTextEmphasisPosition": "over",
    "webkitTextEmphasisStyle": "none",
    "webkitTextFillColor": "rgb(0, 0, 0)",
    "webkitTextOrientation": "vertical-right",
    "webkitTextSecurity": "none",
    "webkitTextSizeAdjust": "auto",
    "webkitTextStroke": "0px rgb(0, 0, 0)",
    "webkitTextStrokeColor": "rgb(0, 0, 0)",
    "webkitTextStrokeWidth": "0px",
    "webkitTransform": "none",
    "webkitTransformOrigin": "476.397px 314.934px",
    "webkitTransformOriginX": "",
    "webkitTransformOriginY": "",
    "webkitTransformOriginZ": "",
    "webkitTransformStyle": "flat",
    "webkitTransition": "all",
    "webkitTransitionDelay": "0s",
    "webkitTransitionDuration": "0s",
    "webkitTransitionProperty": "all",
    "webkitTransitionTimingFunction": "ease",
    "webkitUserDrag": "auto",
    "webkitUserModify": "read-only",
    "webkitUserSelect": "auto",
    "webkitWritingMode": "horizontal-tb",
    "whiteSpace": "normal",
    "whiteSpaceCollapse": "collapse",
    "widows": "2",
    "width": "952.794px",
    "willChange": "auto",
    "wordBreak": "normal",
    "wordSpacing": "0px",
    "wordWrap": "normal",
    "writingMode": "horizontal-tb",
    "x": "0px",
    "y": "0px",
    "zIndex": "auto",
    "zoom": "1"
}

*/